### ISSUE TITLE
Perl for Windows?

### ISSUE THREAD

**Issue by techtonik** [Infinidat/relocatable-python#10]
Why Perl is needed Windows?

**Comment by wiggin15** [comment]
To compile a relocatable python, we compile all of Python's open-source dependencies to pack with it. Some of these dependencies (like openssl) require perl for their configure/make scripts.

**Comment by techtonik** [comment]
Can Perl dependency be included the same way as OpenSSL? I don't see OpenSSL in Windows prerequisites.

**Comment by wiggin15** [comment]
The idea of this project is to build all the Python dependencies (and Python itself) with special configuration that make them relocatable (e.g. we're building the OpenSSL shared library with a custom runtime search path so that it will not depend on absolute paths and on binaries that are installed on the target machine). Since we build OpenSSL as part of the build process, we don't require it. Perl, on the other hand, like Visual Studio, is required to build the shared libraries. We don't need to build Perl during the build process because it's not a Python dependency, and we don't need a special version of it. Perl is a big project that may not be simple to build, and since we don't really need a custom build for the relocatable Python, it makes more sense to require it as a prerequisite instead of building it like OpenSSL.

**Comment by techtonik** [comment]
From a user point of view requirements are requirements, and if you already handle OpenSSL dependency in some way, it doesn't make sense to threat Perl differently. Visual Studio probably can not be installed automatically due to legal and technical restrictions from its company, but Perl..

**Comment by wiggin15** [comment]
We handle OpenSSL and the other Python dependencies because we must - it's what the project does. Building Perl will not make sense for us - it's not what the relocatable python needs (and we only build the dependencies that relocatable python needs) and it will just add more time and complication to the build process (remember, we have to define the configuration for all the platforms, and it's unnecessary if we can just use the pre-built Perl that you can just download and install)... Please notice that there is a difference between the Python dependencies that we compile, and the requirements to compile. We're ok with having Perl as a requirement to the user.
